name: Build

on: [push, pull_request]

env:
  PYICU_VERSION: "2.14"

jobs:
  macos-intel:
    name: Build wheels on macOS (x86_64)
    # macos-13 is an intel runner, macos-14 is apple silicon
    runs-on: macos-13
    strategy:
      matrix:
        arch:
          - "x86_64"
        cpy:
          - "cp310"

    env:
      LIBICU_VERSION: "76"

    steps:
      - uses: actions/checkout@v4

      - name: Fetch source
        run: git clone --branch=v${PYICU_VERSION} --depth=1 https://gitlab.pyicu.org/main/pyicu.git

      - name: Install build dependencies
        run: |
          brew update
          brew install pkgconf icu4c@${LIBICU_VERSION}

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        with:
          package-dir: pyicu
        env:
          CIBW_BUILD: ${{matrix.cpy}}-macosx_${{matrix.arch}}
          CIBW_ARCHS_MACOS: ${{matrix.arch}}
          CIBW_ENVIRONMENT: >-
            MACOSX_DEPLOYMENT_TARGET=13.0
            PKG_CONFIG_PATH="/usr/local/opt/icu4c@${LIBICU_VERSION}/lib/pkgconfig"
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: macos-13-${{matrix.cpy}}-macosx_${{matrix.arch}}
          path: ./wheelhouse/*.whl
